# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015


# 4月1日の間だけ動作させるかどうか。
aprilfoolTimer: true

# 質問をした人と、回答をした人が、もらえる報酬。
award:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND

# 1日に何回まで、報酬を受け取ることができるか。
maxAwardPerDay: 3

# 説明をしてもらう質問文。
questions:
- 'ラッスンゴレライ説明してね'

# 説明に対する回答の正解ワード。
# 質問がされたあとから制限時間以内に、いずれかの正解ワードを含むチャット発言がされたら、
# 質問をした人と回答をした人に報酬が与えられる。
answers:
- 'ちょっと待ってちょっと待ってお兄さん'
- '説明しろと言われましても'
- '意味わからんからできません'
- '南国なん？'
- 'スパイダーフラッシュローリングサンダ'
- 'スパイダーフラッシュローリンサンダ'
- '絶対教えんラッスンゴレライ'

# 質問の時間制限（秒）。
time: 20

# 質問したのに回答が無かったときに、質問者に与えられるペナルティダメージ。
penaltyDamage: 10
